sudo: required
language: ruby

services:
  - docker

install:
  - echo "install nothing"

before_install:
  - docker pull ciriethereum/ciri:latest

script:
  - docker run -v `pwd`:/app --rm ciriethereum/ciri:latest bundle install && bundle exec rake



---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.5
