sudo: required
language: ruby

services:
  - docker

install:
  - echo "install nothing"

before_install:
  - docker pull ciriethereum/ciri:latest

script:
  - docker run -v `pwd`:/app --rm ciriethereum/ciri:latest bash -c 'bundle install && bundle exec rspec'

